name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Set the branch to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r api/requirements.txt
        
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}  # Ensure the root directory is in PYTHONPATH
        CSV_NAMES: "reduced_for_tests"  # Set your custom parameter here
      run: |
        source venv/bin/activate
        pytest

    - name: Zip the codebase
      run: zip -r deployment-package.zip . -x '*.git*'

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/files/path/to/deployment-package.zip" \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
          --data-binary @deployment-package.zip
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/reload/" \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"
